[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

#[build]
#target-dir ="/home/gokhansa/.cargo-target"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "tcp"

[dependencies]
tun-tap = "0.1.3"